name       : haskell-connection
version    : 0.2.7
release    : 1
source     :
    - http://hackage.haskell.org/package/connection-0.2.7/connection-0.2.7.tar.gz : 46d452dc92ebc6e851a9f9ac01dd2d29df846795dfce039cf07ba7102a323235
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple network library for all your connection need. 
description: |
    Simple network library for all your connection need. 
builddeps  :
    - haskell-cabal-install
    - haskell-socks
    - haskell-tls
    - haskell-x509-system
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
