name       : haskell-connection
version    : 0.3.1
release    : 3
source     :
    - https://hackage.haskell.org/package/connection-0.3.1/connection-0.3.1.tar.gz : 5d759589c532c34d87bfc4f6fcb732bf55b55a93559d3b94229e8347a15375d9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple network library for all your connection need.
description: 
    Simple network library for all your connection need.
builddeps  :
    - haskell-cabal-install
    - haskell-socks-devel
    - haskell-tls-devel
    - haskell-x509-system-devel
rundeps    :
    - devel:
        - haskell-socks-devel
        - haskell-tls-devel
        - haskell-x509-system-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
