name       : haskell-connection
version    : 0.2.8
release    : 2
source     :
    - http://hackage.haskell.org/package/connection-0.2.8/connection-0.2.8.tar.gz : 70b1f44e8786320c18b26fc5d4ec115fc8ac016ba1f852fa8137f55d785a93eb
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple network library for all your connection need.
description: "Simple network library for all your connection need. \n"
builddeps  :
    - haskell-byteable
    - haskell-cabal-install
    - haskell-socks
    - haskell-tls
    - haskell-x509-system
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
